-ignorewarnings
-keepattributes *Annotation*
-keepattributes Exceptions
-keepattributes InnerClasses
-keepattributes Signature
-keepattributes SourceFileLineNumberTable
-keep class com.hianalytics.android.**{*;}
-keep class com.lvonasek.arcore3dscanner.main.JNI**
